##### freedns42

freedns42_user: username
freedns42_pass: password


##### freshtomato nvram

wifi_pass_wl1: password
wifi_pass_wl2: password

### wireguard wg0 and wg1

wg0_priv_key: 1234567890
wg0_pub_key: 1234567890
wg0_presh_key_wg0: 1234567890

wg1_priv_key: 1234567890
wg1_pub_key: 1234567890
wg1_presh_key_wg0: 1234567890

