#!/bin/sh

NAME="NETWAIT[$$]"
INTERVAL=3
MAXCOUNT=10

checkdate() {
  local year=$(/bin/date +%Y)
  if [ $year -gt 1970 ]
  then
    return 0
  fi
  return 1
}

# First thing we do is check the current date.  If the year is
# already compliant, then don't call logger or anything else; just
# exit cleanly immediately.

if checkdate; then
  exit 0
fi

# Otherwise use a loop to check things repeatedly and bail out if
# things look good -- or bail out at the very end with a nastygram
# indicating we're not responsible if daemons misbehave past this
# point.  :-)

i=1
while [ $i -le $MAXCOUNT ]
do
  logger -s "$NAME: Waiting for ntpc (attempt ${i}/${MAXCOUNT})"
  sleep $INTERVAL

  if checkdate; then
    logger -s "$NAME: Clock synced; good to go!"
    exit 0
  fi
  i=$((i+1))
done

logger -s "$NAME: Clock remains unsynced; continuing anyway"
exit 1