#!/bin/sh

# /proc tuning adjustments for TomatoUSB

NAME="TUNING[$$]"

start() {
  #
  # Set IPv4 icmp_ratelimit to 0 (no rate limiting) to ensure that outbound
  # mtrs (which repeatedly send ICMP packets to each hop, including the router)
  # aren't affected.
  #
  echo 0 > /proc/sys/net/ipv4/icmp_ratelimit

  #
  # Increase ARP cache sizes and GC thresholds; may alleviate "Neighbour table
  # overflow" warnings that some users are seeing.
  #
  # http://www.linksysinfo.org/index.php?threads/ipv6-and-comcast.38006/page-2#post-184563
  #
  echo  256 > /proc/sys/net/ipv4/neigh/default/gc_thresh1
  echo 1024 > /proc/sys/net/ipv4/neigh/default/gc_thresh2
  echo 2048 > /proc/sys/net/ipv4/neigh/default/gc_thresh3

  #
  # Lower conntrack tcp_timeout_max_retrans from 300 to 240.
  #
  echo 240 > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_max_retrans

  #
  # IPv6 adjustments for some of the above stuff.  NOTE: Pathname for icmp ratelimit
  # differs from IPv4 tunable.
  #
  if [ -n "`nvram get ipv6_service`" ]; then
    echo    0 > /proc/sys/net/ipv6/icmp/ratelimit
    echo  256 > /proc/sys/net/ipv6/neigh/default/gc_thresh1
    echo 1024 > /proc/sys/net/ipv6/neigh/default/gc_thresh2
    echo 2048 > /proc/sys/net/ipv6/neigh/default/gc_thresh3
  fi
}


ACTION=$1
CALLER=$2

case $ACTION in
  start)
    logger -s "$NAME: Adjusting /proc tunables..."
    start
    logger -s "$NAME: Finished adjusting tunables"
    ;;
  stop|check|reconfigure|kill)
    # no-ops
    ;;
  *)
    echo "Usage: $0 start"
    exit 1
    ;;
esac