---

- name: Advanced > Firewall
  ansible.builtin.script: "{{ firewall_nvram }}"
  args: 
    executable: /bin/sh

- name: Commit Advanced > Firewall changes and restart 'firewall' service
  ansible.builtin.shell: |
    nvram commit
    service firewall restart
  args: 
    executable: /bin/sh
