---

# requires 'reboot' task to commit changes and reboot router

- name: Administration > Scripts
  ansible.builtin.shell: "{{ lookup('template', scripts_nvram) }}"
  args: 
    executable: /bin/sh

- name: Administration > Scripts changes
  ansible.builtin.shell: |
    nvram commit
  args: 
    executable: /bin/sh
