---

- name: Check if 'script_usbmount' is declared
  ansible.builtin.set_fact:
    script_usbmount_present: true
  when: script_usbmount is defined and script_usbmount | length > 0

- name: Check if 'script_usbumount' is declared
  ansible.builtin.set_fact:
    script_usbumount_present: true
  when: script_usbumount is defined and script_usbumount | length > 0

- name: Install USB boot scripts
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    decrypt: "{{ item.decrypt }}"
    owner: root 
    group: root 
    mode: "{{ item.mode }}"
  loop: "{{ usb_boot_default_scripts }}"
  when: not script_usbmount_present and not script_usbumount_present

- name: Uninstall USB boot scripts
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: absent
  loop: "{{ usb_boot_default_scripts }}"
  when: script_usbmount_present or script_usbumount_present

- name: Configure USB-NAS > USB Support
  ansible.builtin.shell: "{{ lookup('template', usb_support_nvram) }}"
  args: 
    executable: /bin/sh

- name: Commit USB-NAS > USB Support changes and service usb restart
  ansible.builtin.shell: |
    /opt/etc/init.d/rc.unslung stop
    sleep 5
    nvram commit
    service usb restart
    /opt/mount.autorun
