---

# requires 'reboot' task to commit changes and reboot router

- name: Configure Advanced > Virtual Wireless
  ansible.builtin.shell: "{{ lookup('template', '{{ virtual_wireless_nvram }}') }}"
  args: 
    executable: /bin/sh

- name: Commit Advanced > Virtual Wireless changes
  ansible.builtin.shell: |
    nvram commit
  args: 
    executable: /bin/sh